version: '3.3'
services:
  app:
    image: sugere:1.0
    container_name: 'sugere'
    restart: always
    networks:
      - sugere-net
    build:
      context: ./
      dockerfile: ./docker/sugere/Dockerfile
    env_file:
      - .env
    ports:
      - 80:${PORT}
  
  db:
    image: postgres:14-bullseye
    container_name: 'sugere-db'
    env_file:
      - .env
    volumes:
      - data:/var/lib/postgresql/data
      - ./data/:/docker-entrypoint-initdb.d/
    networks:
      - sugere-net
    ports:
      - ${POSTGRES_PORT}:5432

networks:
  sugere-net:
    
volumes:
  data: